# Generated by Django 4.1.2 on 2022-10-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_note_addnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='addnote',
            name='bookmark',
            field=models.IntegerField(default=0),
        ),
    ]
